
import { Dinosaur, QuizQuestion } from './types';

export const DINOSAURS: Dinosaur[] = [
  // --- Existing Dinosaurs (Updated with new props) ---
  {
    id: 't-rex',
    name: 'Tyrannosaurus Rex',
    pronunciation: 'tie-RAN-oh-sore-us REX',
    meaning: 'Tyrant Lizard King',
    period: 'Late Cretaceous',
    year: 1902,
    diet: 'Carnivore',
    group: 'Theropods',
    length_meters: 12.3,
    weight_tons: 8.4,
    description: 'One of the most ferocious predators to ever walk the Earth. The T-Rex had massive jaws with 60 teeth, some up to 20cm long. Despite its tiny arms, it was a fearsome hunter.',
    habitat: 'Humid, semi-tropical forests',
    location: { name: 'North America (Hell Creek Formation)', lat: 47.0, lng: -106.0 },
    fun_fact: 'A T-Rex bite was more than 3 times powerful than a lion!',
    image_url: 'https://picsum.photos/seed/trex/800/600',
    anatomy: [
      { feature: 'Jaws', description: 'Bone-crushing bite force of nearly 12,800 pounds.' },
      { feature: 'Eyes', description: 'Forward-facing eyes giving it binocular vision better than a hawk.' },
      { feature: 'Arms', description: 'Small but extremely muscular, possibly used to hold struggling prey.' }
    ],
    stats: { intelligence: 7, speed: 6, defense: 5, attack: 10 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'spinosaurus',
    name: 'Spinosaurus',
    pronunciation: 'SPINE-oh-SORE-us',
    meaning: 'Spine Lizard',
    period: 'Cretaceous',
    year: 1915,
    diet: 'Carnivore',
    group: 'Spinosaurs',
    length_meters: 15,
    weight_tons: 7,
    description: 'The largest carnivorous dinosaur, even bigger than T-Rex. It had a massive sail on its back and a crocodile-like snout for catching fish. Recent discoveries suggest it was semi-aquatic.',
    habitat: 'Swamps and river deltas',
    location: { name: 'North Africa (Sahara)', lat: 27.0, lng: 30.0 },
    fun_fact: 'It is the only known dinosaur that was adapted to a semi-aquatic lifestyle, swimming with a paddle-like tail.',
    image_url: 'https://picsum.photos/seed/spinosaurus/800/600',
    anatomy: [
      { feature: 'Sail', description: 'Tall spines up to 1.65 meters long connected by skin, likely for display.' },
      { feature: 'Snout', description: 'Long and narrow with conical teeth, perfect for gripping slippery fish.' },
      { feature: 'Tail', description: 'Paddle-like structure used for propulsion in water.' }
    ],
    stats: { intelligence: 6, speed: 5, defense: 4, attack: 9 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Water'
  },
  {
    id: 'baryonyx',
    name: 'Baryonyx',
    pronunciation: 'BAR-ee-ON-iks',
    meaning: 'Heavy Claw',
    period: 'Early Cretaceous',
    year: 1983,
    diet: 'Carnivore',
    group: 'Spinosaurs',
    length_meters: 9.5,
    weight_tons: 1.7,
    description: 'A semi-aquatic carnivore from Europe with a crocodile-like head and a massive 30cm-long thumb claw. It likely specialized in catching fish from prehistoric rivers.',
    habitat: 'River banks and lakesides',
    location: { name: 'Europe (Surrey, UK)', lat: 51.2, lng: -0.3 },
    fun_fact: 'Fossilized fish scales were found inside the stomach area of the first Baryonyx skeleton!',
    image_url: 'https://picsum.photos/seed/baryonyx/800/600',
    anatomy: [
      { feature: 'Thumb Claw', description: 'A massive curved claw used to gaff fish out of the water.' },
      { feature: 'Snout', description: 'Long, low snout with 96 teeth—more than twice as many as T-Rex.' },
      { feature: 'Neck', description: 'Less "S" shaped than other theropods, better for striking downward into water.' }
    ],
    stats: { intelligence: 6, speed: 7, defense: 4, attack: 8 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Water'
  },
  {
    id: 'pachycephalosaurus',
    name: 'Pachycephalosaurus',
    pronunciation: 'pak-ee-SEF-a-lo-SORE-us',
    meaning: 'Thick-headed Lizard',
    period: 'Late Cretaceous',
    year: 1943,
    diet: 'Herbivore',
    group: 'Pachycephalosaurs',
    length_meters: 4.5,
    weight_tons: 0.45,
    description: 'A unique dinosaur famous for its extremely thick skull roof, which was up to 25 centimeters (10 inches) thick. It likely used its head for defense or head-butting rituals.',
    habitat: 'Forests and plains',
    location: { name: 'North America (South Dakota)', lat: 44.5, lng: -101.5 },
    fun_fact: 'Its dome-shaped skull was made of solid bone, acting like a built-in helmet!',
    image_url: 'https://picsum.photos/seed/pachy/800/600',
    anatomy: [
      { feature: 'Bony Dome', description: 'A massive, thickened skull roof used for combat or display.' },
      { feature: 'Spikes', description: 'Small bony spikes and knobs surrounding the base of the skull dome.' },
      { feature: 'Stance', description: 'Bipedal dinosaur with strong legs for sprinting and stability.' }
    ],
    stats: { intelligence: 4, speed: 7, defense: 9, attack: 6 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'homalocephale',
    name: 'Homalocephale',
    pronunciation: 'ho-MAL-o-SEFF-ah-lee',
    meaning: 'Even Head',
    period: 'Late Cretaceous',
    year: 1974,
    diet: 'Herbivore',
    group: 'Pachycephalosaurs',
    length_meters: 1.8,
    weight_tons: 0.04,
    description: 'Unlike its dome-headed relatives, Homalocephale had a flat, wedge-shaped skull roof. It lived in Asia and was a small, agile runner.',
    habitat: 'Arid plains and scrublands',
    location: { name: 'Asia (Gobi Desert, Mongolia)', lat: 44.0, lng: 103.0 },
    fun_fact: 'It had a very wide pelvis, suggesting it might have given birth to live young or had very large eggs!',
    image_url: 'https://picsum.photos/seed/homalo/800/600',
    anatomy: [
      { feature: 'Flat Skull', description: 'A thick but flat skull roof, heavily pitted with small holes.' },
      { feature: 'Wide Hips', description: 'Unusually broad pelvis for its small size.' },
      { feature: 'Long Legs', description: 'Adapted for high-speed evasion of predators.' }
    ],
    stats: { intelligence: 5, speed: 9, defense: 6, attack: 3 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'stegoceras',
    name: 'Stegoceras',
    pronunciation: 'steg-OSS-er-as',
    meaning: 'Horned Roof',
    period: 'Late Cretaceous',
    year: 1902,
    diet: 'Herbivore',
    group: 'Pachycephalosaurs',
    length_meters: 2,
    weight_tons: 0.05,
    description: 'A smaller relative of Pachycephalosaurus, Stegoceras was one of the first dome-headed dinosaurs discovered. It was agile and likely lived in upland areas.',
    habitat: 'Uplands and dry forests',
    location: { name: 'North America (Alberta, Canada)', lat: 51.0, lng: -114.0 },
    fun_fact: 'Despite its small size, its skull was very dense and designed to absorb high-impact collisions.',
    image_url: 'https://picsum.photos/seed/stegoceras/800/600',
    anatomy: [
      { feature: 'Skull Dome', description: 'Highly vascularized bone dome, potentially used for species recognition.' },
      { feature: 'Large Eyes', description: 'Suggests excellent vision for spotting predators in hilly terrain.' },
      { feature: 'Stiff Tail', description: 'Used for balance during high-speed maneuvers.' }
    ],
    stats: { intelligence: 5, speed: 9, defense: 7, attack: 4 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'triceratops',
    name: 'Triceratops',
    pronunciation: 'try-SAIR-uh-tops',
    meaning: 'Three-horned Face',
    period: 'Late Cretaceous',
    year: 1887,
    diet: 'Herbivore',
    group: 'Ceratopsians',
    length_meters: 9,
    weight_tons: 10,
    description: 'Recognizable by its massive frill and three horns, the Triceratops was like a prehistoric rhinoceros. It likely used its horns for defense against predators like T-Rex.',
    habitat: 'Forests and plains',
    location: { name: 'North America (Wyoming)', lat: 42.0, lng: -107.0 },
    fun_fact: 'Its head was one of the largest of any land animal, making up one-third of its entire body length.',
    image_url: 'https://picsum.photos/seed/triceratops/800/600',
    anatomy: [
      { feature: 'Horns', description: 'Two long brow horns and one short nose horn used for defense and display.' },
      { feature: 'Frill', description: 'Solid bone shield protecting the neck, possibly changed color for display.' },
      { feature: 'Beak', description: 'Parrot-like beak for shearing through tough vegetation.' }
    ],
    stats: { intelligence: 4, speed: 4, defense: 9, attack: 6 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'styracosaurus',
    name: 'Styracosaurus',
    pronunciation: 'sty-RAK-oh-sore-us',
    meaning: 'Spiked Lizard',
    period: 'Late Cretaceous',
    year: 1913,
    diet: 'Herbivore',
    group: 'Ceratopsians',
    length_meters: 5.5,
    weight_tons: 2.7,
    description: 'A close relative of Triceratops, but with a more spectacular display. It had one long nose horn and a frill adorned with four to six long spikes.',
    habitat: 'Woodlands',
    location: { name: 'North America (Alberta, Canada)', lat: 50.5, lng: -111.0 },
    fun_fact: 'Its frill spikes could grow as long as the horn on its nose!',
    image_url: 'https://picsum.photos/seed/styraco/800/600',
    anatomy: [
      { feature: 'Nose Horn', description: 'A single, massive horn up to 60cm long.' },
      { feature: 'Frill Spikes', description: 'Long parietal spikes radiating from the neck shield.' },
      { feature: 'Beak', description: 'Powerful beak for slicing through fibrous plants.' }
    ],
    stats: { intelligence: 3, speed: 5, defense: 9, attack: 7 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'ankylosaurus',
    name: 'Ankylosaurus',
    pronunciation: 'an-KIE-lo-SORE-us',
    meaning: 'Fused Lizard',
    period: 'Late Cretaceous',
    year: 1908,
    diet: 'Herbivore',
    group: 'Ankylosaurs',
    length_meters: 8,
    weight_tons: 6,
    description: 'The ultimate tank of the dinosaur world. It was covered in heavy bony plates and had a massive club at the end of its tail that could easily break a predator\'s leg.',
    habitat: 'Coastal plains',
    location: { name: 'North America (Montana)', lat: 46.5, lng: -110.0 },
    fun_fact: 'Even its eyelids were made of bone to protect its eyes from attacks!',
    image_url: 'https://picsum.photos/seed/ankylosaurus/800/600',
    anatomy: [
      { feature: 'Tail Club', description: 'Made of two large bony lumps, used to deliver crushing blows to predators.' },
      { feature: 'Armor', description: 'Known as osteoderms, these bony plates were embedded in the skin.' },
      { feature: 'Beak', description: 'Used to crop low-growing vegetation near the ground.' }
    ],
    stats: { intelligence: 3, speed: 2, defense: 10, attack: 7 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'iguanodon',
    name: 'Iguanodon',
    pronunciation: 'ig-WA-no-don',
    meaning: 'Iguana Tooth',
    period: 'Early Cretaceous',
    year: 1825,
    diet: 'Herbivore',
    group: 'Ornithopods',
    length_meters: 10,
    weight_tons: 4,
    description: 'A large, versatile herbivore that could walk on either two or four legs. It had a unique conical spike on its thumb, which it used for defense and foraging.',
    habitat: 'Woodlands and riversides',
    location: { name: 'Europe (Belgium/UK)', lat: 50.5, lng: 4.5 },
    fun_fact: 'Iguanodon was the second dinosaur ever to be scientifically named.',
    image_url: 'https://picsum.photos/seed/iguanodon/800/600',
    anatomy: [
      { feature: 'Thumb Spike', description: 'A sharp spike on the first digit used as a defensive weapon.' },
      { feature: 'Teeth', description: 'Leaf-shaped teeth designed for grinding tough plant material.' },
      { feature: 'Prehensile Pinky', description: 'A fifth finger capable of wrapping around and manipulating food.' }
    ],
    stats: { intelligence: 5, speed: 6, defense: 6, attack: 5 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'velociraptor',
    name: 'Velociraptor',
    pronunciation: 'veh-LOSS-ih-rap-tor',
    meaning: 'Swift Seizer',
    period: 'Late Cretaceous',
    year: 1924,
    diet: 'Carnivore',
    group: 'Theropods',
    length_meters: 2,
    weight_tons: 0.015,
    description: 'Smaller than depicted in movies, the Velociraptor was a turkey-sized, feathered predator. Intelligent and agile, it hunted in packs using its deadly sickle claws.',
    habitat: 'Deserts and sand dunes',
    location: { name: 'Mongolia (Gobi Desert)', lat: 44.0, lng: 103.0 },
    fun_fact: 'Velociraptors were covered in feathers, much like modern birds.',
    image_url: 'https://picsum.photos/seed/velociraptor/800/600',
    anatomy: [
      { feature: 'Sickle Claw', description: 'A retractable, curved claw on the second toe used to pin prey.' },
      { feature: 'Feathers', description: 'Had wing feathers, though it could not fly. Used for warmth or display.' },
      { feature: 'Tail', description: 'Stiffened by bony rods to help balance while running and turning.' }
    ],
    stats: { intelligence: 9, speed: 10, defense: 2, attack: 7 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'brachiosaurus',
    name: 'Brachiosaurus',
    pronunciation: 'brak-ee-oh-SORE-us',
    meaning: 'Arm Lizard',
    period: 'Late Jurassic',
    year: 1903,
    diet: 'Herbivore',
    group: 'Sauropods',
    length_meters: 26,
    weight_tons: 50,
    description: 'A colossal sauropod with longer front legs than back legs, giving it a giraffe-like stance. It could reach high vegetation that other herbivores couldn\'t touch.',
    habitat: 'Floodplains and forests',
    location: { name: 'North America (Colorado)', lat: 39.0, lng: -108.0 },
    fun_fact: 'Its heart had to be massive to pump blood up its long neck to its brain.',
    image_url: 'https://picsum.photos/seed/brachiosaurus/800/600',
    anatomy: [
      { feature: 'Neck', description: 'Could reach up to 9 meters high to eat from tree canopies.' },
      { feature: 'Nostrils', description: 'Located on the top of its head, leading to early theories it lived underwater.' },
      { feature: 'Teeth', description: 'Chisel-like teeth designed for stripping leaves, not chewing.' }
    ],
    stats: { intelligence: 3, speed: 2, defense: 8, attack: 3 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'diplodocus',
    name: 'Diplodocus',
    pronunciation: 'dih-PLOD-oh-kus',
    meaning: 'Double Beam',
    period: 'Late Jurassic',
    year: 1878,
    diet: 'Herbivore',
    group: 'Sauropods',
    length_meters: 25,
    weight_tons: 15,
    description: 'One of the longest dinosaurs to ever live. It had a whip-like tail that it could crack at supersonic speeds to scare off predators.',
    habitat: 'Semi-arid plains',
    location: { name: 'North America (Colorado)', lat: 38.5, lng: -105.5 },
    fun_fact: 'Its tail contained around 80 vertebrae, double that of some other sauropods.',
    image_url: 'https://picsum.photos/seed/diplodocus/800/600',
    anatomy: [
      { feature: 'Whip Tail', description: 'Used for defense and possibly communication.' },
      { feature: 'Peg Teeth', description: 'Designed to strip leaves off branches like a rake.' },
      { feature: 'Neck', description: 'Held mostly horizontal to graze large areas of ferns.' }
    ],
    stats: { intelligence: 2, speed: 3, defense: 8, attack: 4 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'giganotosaurus',
    name: 'Giganotosaurus',
    pronunciation: 'jig-a-NOT-o-SORE-us',
    meaning: 'Giant Southern Lizard',
    period: 'Late Cretaceous',
    year: 1993,
    diet: 'Carnivore',
    group: 'Theropods',
    length_meters: 13,
    weight_tons: 8.8,
    description: 'One of the few meat-eaters that could rival the T-Rex in size. Living in South America, it likely hunted the massive sauropods that shared its habitat.',
    habitat: 'Open grasslands',
    location: { name: 'South America (Argentina)', lat: -39.0, lng: -68.0 },
    fun_fact: 'It could run at speeds up to 31 miles per hour (50 km/h)!',
    image_url: 'https://picsum.photos/seed/giga/800/600',
    anatomy: [
      { feature: 'Brain', description: 'Relatively small, about the size of a banana.' },
      { feature: 'Teeth', description: 'Saw-like teeth designed for slicing through meat rather than crushing bone.' },
      { feature: 'Feet', description: 'Three-toed feet with large claws for stability during high-speed chases.' }
    ],
    stats: { intelligence: 5, speed: 8, defense: 4, attack: 9 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'stegosaurus',
    name: 'Stegosaurus',
    pronunciation: 'steg-uh-SORE-us',
    meaning: 'Roof Lizard',
    period: 'Late Jurassic',
    year: 1877,
    diet: 'Herbivore',
    group: 'Stegosaurs',
    length_meters: 9,
    weight_tons: 5,
    description: 'Famous for the double row of kite-shaped plates along its back and the four spikes on its tail. It had a brain roughly the size of a walnut.',
    habitat: 'Open plains',
    location: { name: 'North America (Colorado)', lat: 40.5, lng: -105.5 },
    fun_fact: 'The spikes on its tail are called a "thagomizer".',
    image_url: 'https://picsum.photos/seed/stegosaurus/800/600',
    anatomy: [
      { feature: 'Plates', description: 'Bony plates embedded in skin, likely for thermoregulation or display.' },
      { feature: 'Thagomizer', description: 'Four spikes at the end of the tail used as a defensive weapon.' },
      { feature: 'Brain', description: 'Extremely small brain for its body size.' }
    ],
    stats: { intelligence: 1, speed: 3, defense: 10, attack: 5 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'muttaburrasaurus',
    name: 'Muttaburrasaurus',
    pronunciation: 'MUT-a-BUR-a-SORE-us',
    meaning: 'Lizard from Muttaburra',
    period: 'Early Cretaceous',
    year: 1963,
    diet: 'Herbivore',
    group: 'Ornithopods',
    length_meters: 8,
    weight_tons: 2.8,
    description: 'A distinctively Australian dinosaur with a large, hollow bump on its nose. It was related to Iguanodon but had different teeth adapted for tough vegetation.',
    habitat: 'Floodplains and forests',
    location: { name: 'Australia (Queensland)', lat: -22.5, lng: 144.5 },
    fun_fact: 'The bump on its nose might have been used to produce loud calls to communicate with other dinosaurs!',
    image_url: 'https://picsum.photos/seed/mutta/800/600',
    anatomy: [
      { feature: 'Nasal Bump', description: 'Hollow structure likely used for resonance and sound production.' },
      { feature: 'Beak', description: 'Strong beak for stripping bark and ferns.' },
      { feature: 'Stance', description: 'Facultative biped - walked on four legs but could run on two.' }
    ],
    stats: { intelligence: 6, speed: 5, defense: 5, attack: 3 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'parasaurolophus',
    name: 'Parasaurolophus',
    pronunciation: 'par-ah-saw-ROL-oh-fus',
    meaning: 'Near Crested Lizard',
    period: 'Late Cretaceous',
    year: 1922,
    diet: 'Herbivore',
    group: 'Ornithopods',
    length_meters: 9.5,
    weight_tons: 2.5,
    description: 'Famous for its long, tubular crest which swept back from its skull. This crest was hollow and connected to the nasal passages, allowing it to produce loud, resonating calls.',
    habitat: 'Floodplains and lush forests',
    location: { name: 'North America (Alberta, Canada)', lat: 51.5, lng: -112.0 },
    fun_fact: 'Computer simulations suggest its crest could produce sounds similar to a deep trombone!',
    image_url: 'https://picsum.photos/seed/parasaura/800/600',
    anatomy: [
      { feature: 'Crest', description: 'A hollow tube up to 1.8 meters long used for communication and display.' },
      { feature: 'Duck Bill', description: 'A toothless beak used to crop vegetation.' },
      { feature: 'Tail', description: 'Deep and flattened, useful for balance and swimming.' }
    ],
    stats: { intelligence: 5, speed: 5, defense: 4, attack: 2 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'corythosaurus',
    name: 'Corythosaurus',
    pronunciation: 'ko-RITH-o-sore-us',
    meaning: 'Helmet Lizard',
    period: 'Late Cretaceous',
    year: 1914,
    diet: 'Herbivore',
    group: 'Ornithopods',
    length_meters: 9,
    weight_tons: 4,
    description: 'Easily identified by the semi-circular, plate-like crest on its head that looked like a Corinthian soldier\'s helmet. It was a social dinosaur that lived in herds.',
    habitat: 'Coastal forests and swamps',
    location: { name: 'North America (Alberta, Canada)', lat: 50.8, lng: -111.5 },
    fun_fact: 'We know exactly what its skin looked like because fossilized skin impressions have been found!',
    image_url: 'https://picsum.photos/seed/corytho/800/600',
    anatomy: [
      { feature: 'Helmet Crest', description: 'A hollow, bony crest containing nasal passages for making sounds.' },
      { feature: 'Dental Battery', description: 'Hundreds of small teeth packed together to grind tough plants.' },
      { feature: 'Skin', description: 'Covered in small, pebble-like scales that did not overlap.' }
    ],
    stats: { intelligence: 4, speed: 5, defense: 3, attack: 2 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'gallimimus',
    name: 'Gallimimus',
    pronunciation: 'GAL-ih-MY-mus',
    meaning: 'Chicken Mimic',
    period: 'Late Cretaceous',
    year: 1972,
    diet: 'Omnivore',
    group: 'Theropods',
    length_meters: 6,
    weight_tons: 0.44,
    description: 'An extremely fast, ostrich-like dinosaur. It lacked teeth and likely ate a variety of foods including plants, insects, and small animals.',
    habitat: 'Arid deserts and river basins',
    location: { name: 'Asia (Gobi Desert)', lat: 44.0, lng: 105.0 },
    fun_fact: 'It is one of the fastest dinosaurs, capable of reaching speeds over 50 km/h!',
    image_url: 'https://picsum.photos/seed/galli/800/600',
    anatomy: [
      { feature: 'Toothless Beak', description: 'A keratinous beak used for foraging a wide range of food sources.' },
      { feature: 'Long Neck', description: 'Flexible neck for high visibility and reaching food on the ground.' },
      { feature: 'Slender Legs', description: 'Long, bird-like legs designed for high-speed running.' }
    ],
    stats: { intelligence: 6, speed: 10, defense: 3, attack: 3 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'gigantoraptor',
    name: 'Gigantoraptor',
    pronunciation: 'jie-GAN-toe-RAP-tor',
    meaning: 'Giant Seizer',
    period: 'Late Cretaceous',
    year: 2005,
    diet: 'Omnivore',
    group: 'Theropods',
    length_meters: 8,
    weight_tons: 2,
    description: 'A colossal bird-like dinosaur. Though it belonged to the oviraptor group, it was much larger than its relatives, reaching the height of a giraffe.',
    habitat: 'Arid scrublands',
    location: { name: 'Asia (Inner Mongolia)', lat: 43.0, lng: 112.0 },
    fun_fact: 'Despite its fierce name, it likely had a beak and feathers like a giant bird!',
    image_url: 'https://picsum.photos/seed/giganto/800/600',
    anatomy: [
      { feature: 'Beak', description: 'Toothless, strong beak for eating a variety of foods.' },
      { feature: 'Bird-like Limbs', description: 'Long legs for efficient walking across vast distances.' },
      { feature: 'Feathers', description: 'Likely had extensive feathering for display or temperature regulation.' }
    ],
    stats: { intelligence: 7, speed: 7, defense: 4, attack: 6 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'minmi',
    name: 'Minmi',
    pronunciation: 'MIN-mie',
    meaning: 'From Minmi Crossing',
    period: 'Early Cretaceous',
    year: 1980,
    diet: 'Herbivore',
    group: 'Ankylosaurs',
    length_meters: 3,
    weight_tons: 0.3,
    description: 'A small Australian ankylosaur. It had unique horizontal bony plates along its spine for protection, making it more flexible than other armored dinosaurs.',
    habitat: 'Floodplains and forests',
    location: { name: 'Australia (Queensland)', lat: -26.0, lng: 149.0 },
    fun_fact: 'Minmi has the shortest name of any dinosaur!',
    image_url: 'https://picsum.photos/seed/minmi/800/600',
    anatomy: [
      { feature: 'Paravertebral Ossicles', description: 'Unique small bones along the spine for armor and support.' },
      { feature: 'Small Brain', description: 'One of the lowest brain-to-body ratios among dinosaurs.' },
      { feature: 'Low Profile', description: 'Short legs kept it close to the ground for grazing.' }
    ],
    stats: { intelligence: 2, speed: 4, defense: 8, attack: 3 },
    showOnMap: true,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'mosasaurus',
    name: 'Mosasaurus',
    pronunciation: 'MO-zah-SORE-us',
    meaning: 'Meuse River Lizard',
    period: 'Late Cretaceous',
    year: 1764,
    diet: 'Carnivore',
    group: 'Marine Reptiles',
    length_meters: 17,
    weight_tons: 15,
    description: 'Not technically a dinosaur, but a colossal marine reptile. It was the apex predator of the ancient seas, hunting sharks, large fish, and other marine reptiles.',
    habitat: 'Oceans',
    location: { name: 'Western Europe (The Netherlands)', lat: 50.8, lng: 5.7 },
    fun_fact: 'It gave birth to live young in the water rather than laying eggs on land.',
    image_url: 'https://picsum.photos/seed/mosasaurus/800/600',
    anatomy: [
      { feature: 'Jaws', description: 'Double-hinged jaws allowing it to swallow massive prey whole.' },
      { feature: 'Teeth', description: 'Had a second set of teeth in the roof of its mouth.' },
      { feature: 'Flippers', description: 'Modified limbs for steering, while the tail provided propulsion.' }
    ],
    stats: { intelligence: 5, speed: 8, defense: 6, attack: 10 },
    showOnMap: true,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'plesiosaurus',
    name: 'Plesiosaurus',
    pronunciation: 'PLEE-zee-oh-sore-us',
    meaning: 'Near Lizard',
    period: 'Early Jurassic',
    year: 1821,
    diet: 'Carnivore',
    group: 'Marine Reptiles',
    length_meters: 3.5,
    weight_tons: 0.5,
    description: 'A marine reptile with a broad flat body, short tail, and long neck. It "flew" through the water using four large flippers.',
    habitat: 'Shallow seas',
    location: { name: 'Europe (Dorset, UK)', lat: 50.7, lng: -2.9 },
    fun_fact: 'It is often cited as the inspiration for the Loch Ness Monster legend.',
    image_url: 'https://picsum.photos/seed/plesio/800/600',
    anatomy: [
      { feature: 'Flippers', description: 'Four paddle-like limbs used for underwater flight.' },
      { feature: 'Neck', description: 'Extremely long neck to ambush schools of fish.' },
      { feature: 'Teeth', description: 'Needle-like teeth that interlocked to trap slippery prey.' }
    ],
    stats: { intelligence: 4, speed: 7, defense: 3, attack: 6 },
    showOnMap: true,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'pteranodon',
    name: 'Pteranodon',
    pronunciation: 'ter-AN-oh-don',
    meaning: 'Winged and Toothless',
    period: 'Late Cretaceous',
    year: 1876,
    diet: 'Carnivore',
    group: 'Pterosaurs',
    length_meters: 6,
    weight_tons: 0.025,
    description: 'A large flying reptile with a distinctive head crest. It soared over oceans hunting for fish. Though often grouped with dinosaurs, it is a pterosaur.',
    habitat: 'Coastal regions',
    location: { name: 'North America (Kansas)', lat: 39.0, lng: -98.0 },
    fun_fact: 'Males likely had much larger crests than females, used for display.',
    image_url: 'https://picsum.photos/seed/pteranodon/800/600',
    anatomy: [
      { feature: 'Crest', description: 'Bony projection on the back of the head.' },
      { feature: 'Beak', description: 'Toothless and pointed, ideal for snatching fish.' },
      { feature: 'Wings', description: 'Membrane of skin stretching from an elongated fourth finger to its legs.' }
    ],
    stats: { intelligence: 6, speed: 9, defense: 1, attack: 5 },
    showOnMap: true,
    hipAnatomy: 'Other',
    environment: 'Sky'
  },
  {
    id: 'quetzalcoatlus',
    name: 'Quetzalcoatlus',
    pronunciation: 'KWET-zal-co-AT-lus',
    meaning: 'Aztec Feathered Serpent God',
    period: 'Late Cretaceous',
    year: 1971,
    diet: 'Carnivore',
    group: 'Pterosaurs',
    length_meters: 11,
    weight_tons: 0.25,
    description: 'The largest flying animal of all time. Standing as tall as a giraffe when on the ground, this pterosaur was a giant that likely stalked the land for small prey.',
    habitat: 'Inland semi-arid plains',
    location: { name: 'North America (Texas/Mexico)', lat: 29.0, lng: -103.0 },
    fun_fact: 'Its wingspan was as wide as a small airplane!',
    image_url: 'https://picsum.photos/seed/quetzal/800/600',
    anatomy: [
      { feature: 'Long Neck', description: 'Stiff, long neck that allowed it to probe for food like a modern stork.' },
      { feature: 'Beak', description: 'Massive, toothless beak used to swallow prey whole.' },
      { feature: 'Launch Muscles', description: 'Used a powerful four-legged "pole vault" to launch into the air.' }
    ],
    stats: { intelligence: 7, speed: 8, defense: 2, attack: 7 },
    showOnMap: true,
    hipAnatomy: 'Other',
    environment: 'Sky'
  },
  {
    id: 'argentinosaurus',
    name: 'Argentinosaurus',
    pronunciation: 'ar-jen-TEEN-oh-sore-us',
    meaning: 'Argentina Lizard',
    period: 'Late Cretaceous',
    year: 1993,
    diet: 'Herbivore',
    group: 'Sauropods',
    length_meters: 35,
    weight_tons: 100,
    description: 'Widely considered the largest and heaviest land animal to ever exist. This massive sauropod shook the ground as it walked, protecting itself from predators simply by being too big to attack.',
    habitat: 'Forests and floodplains',
    location: { name: 'South America (Argentina)', lat: -38.0, lng: -69.0 },
    fun_fact: 'A single vertebrae from its backbone was over 1.5 meters (5 feet) tall!',
    image_url: 'https://picsum.photos/seed/argentino/800/600',
    anatomy: [
      { feature: 'Size', description: 'So massive that it likely had no natural predators as an adult.' },
      { feature: 'Legs', description: 'Tree-trunk like legs needed to support its immense weight.' },
      { feature: 'Heart', description: 'Would have needed a massive heart to pump blood to its head.' }
    ],
    stats: { intelligence: 2, speed: 1, defense: 10, attack: 2 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'titanosaurus',
    name: 'Titanosaurus',
    pronunciation: 'tie-TAN-o-sore-us',
    meaning: 'Titanic Lizard',
    period: 'Late Cretaceous',
    year: 1877,
    diet: 'Herbivore',
    group: 'Sauropods',
    length_meters: 12,
    weight_tons: 13,
    description: 'The namesake of the Titanosaur group. Unlike earlier sauropods, Titanosaurs often had armored skin (osteoderms) to protect them from predators.',
    habitat: 'Hot, semi-arid plains',
    location: { name: 'India (Lameta Formation)', lat: 23.0, lng: 78.0 },
    fun_fact: 'It was the first dinosaur ever discovered in India!',
    image_url: 'https://picsum.photos/seed/titanosaurus/800/600',
    anatomy: [
      { feature: 'Osteoderms', description: 'Bony plates embedded in the skin for armor.' },
      { feature: 'Broad Chest', description: 'A wide stance compared to other sauropods.' },
      { feature: 'Tail', description: 'Flexible tail potentially used as a defensive weapon.' }
    ],
    stats: { intelligence: 2, speed: 3, defense: 7, attack: 3 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'suchomimus',
    name: 'Suchomimus',
    pronunciation: 'SOO-ko-MY-mus',
    meaning: 'Crocodile Mimic',
    period: 'Early Cretaceous',
    year: 1998,
    diet: 'Carnivore',
    group: 'Spinosaurs',
    length_meters: 11,
    weight_tons: 4,
    description: 'A close relative of the Spinosaurus, but without the massive sail. It had a very long, crocodile-like snout filled with conical teeth designed for gripping slippery fish.',
    habitat: 'Swamps and river deltas',
    location: { name: 'Africa (Niger)', lat: 17.0, lng: 8.0 },
    fun_fact: 'It had over 100 teeth in its long jaws!',
    image_url: 'https://picsum.photos/seed/suchomimus/800/600',
    anatomy: [
      { feature: 'Snout', description: 'Extremely long and narrow, perfect for snatching fish.' },
      { feature: 'Claws', description: 'Large curved claws on its hands for catching prey.' },
      { feature: 'Neural Spines', description: 'Small ridge on its back, unlike the huge sail of Spinosaurus.' }
    ],
    stats: { intelligence: 5, speed: 6, defense: 4, attack: 8 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Water'
  },
  {
    id: 'allosaurus',
    name: 'Allosaurus',
    pronunciation: 'AL-oh-sore-us',
    meaning: 'Different Lizard',
    period: 'Late Jurassic',
    year: 1877,
    diet: 'Carnivore',
    group: 'Theropods',
    length_meters: 8.5,
    weight_tons: 2.3,
    description: 'The "lion of the Jurassic", Allosaurus was the most common large predator of its time. It hunted huge herbivores like Stegosaurus and Diplodocus.',
    habitat: 'Open floodplains',
    location: { name: 'North America (Morrison Formation)', lat: 39.5, lng: -110.0 },
    fun_fact: 'It could open its jaws extremely wide, like a snake, to strike at large prey!',
    image_url: 'https://picsum.photos/seed/allosaurus/800/600',
    anatomy: [
      { feature: 'Horns', description: 'Small horns above the eyes, likely for display or sun-shading.' },
      { feature: 'Arms', description: 'Powerful arms with massive, curved claws for grappling prey.' },
      { feature: 'Teeth', description: 'Serrated teeth that curve backward to prevent prey from escaping.' }
    ],
    stats: { intelligence: 5, speed: 7, defense: 4, attack: 8 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'megalosaurus',
    name: 'Megalosaurus',
    pronunciation: 'MEG-ah-lo-SORE-us',
    meaning: 'Great Lizard',
    period: 'Middle Jurassic',
    year: 1824,
    diet: 'Carnivore',
    group: 'Theropods',
    length_meters: 9,
    weight_tons: 1.1,
    description: 'Historically significant as the very first dinosaur to be scientifically named. It was a typical large theropod that roamed Europe, hunting Stegosaurs and Sauropods.',
    habitat: 'Coastal environments',
    location: { name: 'Europe (Oxfordshire, UK)', lat: 51.8, lng: -1.3 },
    fun_fact: 'When first discovered, a piece of its thigh bone was mistaken for a giant human\'s testicle!',
    image_url: 'https://picsum.photos/seed/megalosaurus/800/600',
    anatomy: [
      { feature: 'Teeth', description: 'Blade-like teeth with serrated edges for slicing meat.' },
      { feature: 'Legs', description: 'Muscular legs built for chasing down prey.' },
      { feature: 'Tail', description: 'Long and heavy to counterbalance its large head and body.' }
    ],
    stats: { intelligence: 4, speed: 6, defense: 3, attack: 7 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'rajasaurus',
    name: 'Rajasaurus',
    pronunciation: 'RAH-jah-SORE-us',
    meaning: 'Princely Lizard',
    period: 'Late Cretaceous',
    year: 2003,
    diet: 'Carnivore',
    group: 'Theropods',
    length_meters: 6.6,
    weight_tons: 1.1,
    description: 'A stocky, powerful meat-eater from India. It had a unique crest on its head and very short arms, typical of abelisaurids. It likely hunted the Titanosaurs that shared its environment.',
    habitat: 'River valleys and floodplains',
    location: { name: 'India (Gujarat)', lat: 23.0, lng: 72.0 },
    fun_fact: 'It is one of the few carnivorous dinosaurs known from India!',
    image_url: 'https://picsum.photos/seed/rajasaurus/800/600',
    anatomy: [
      { feature: 'Head Crest', description: 'A distinctive horn-like crest on the top of its skull.' },
      { feature: 'Jaws', description: 'Powerful jaws designed for gripping and tearing prey.' },
      { feature: 'Body', description: 'Heavy and muscular build compared to other theropods of similar length.' }
    ],
    stats: { intelligence: 4, speed: 6, defense: 5, attack: 8 },
    showOnMap: true,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },

  // --- NEW DINOSAURS (NOT ON MAP) ---

  // Marine Reptiles
  {
    id: 'elasmosaurus',
    name: 'Elasmosaurus',
    pronunciation: 'ee-LAZ-mo-SORE-us',
    meaning: 'Ribbon Lizard',
    period: 'Late Cretaceous',
    year: 1868,
    diet: 'Carnivore',
    group: 'Marine Reptiles',
    length_meters: 14,
    weight_tons: 2,
    description: 'A marine reptile with an extremely long neck that made up half of its total length. It lived in the Western Interior Seaway of North America.',
    habitat: 'Open oceans',
    location: { name: 'North America', lat: 39.0, lng: -98.0 },
    fun_fact: 'Its neck contained over 70 vertebrae—more than any other animal!',
    image_url: 'https://picsum.photos/seed/elasmosaurus/800/600',
    anatomy: [{ feature: 'Neck', description: 'Incredibly long for ambush hunting.' }],
    stats: { intelligence: 4, speed: 6, defense: 2, attack: 5 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'pliosaurus',
    name: 'Pliosaurus',
    pronunciation: 'ply-oh-SORE-us',
    meaning: 'More Lizard',
    period: 'Late Jurassic',
    year: 1841,
    diet: 'Carnivore',
    group: 'Marine Reptiles',
    length_meters: 10,
    weight_tons: 12,
    description: 'A fearsome predator known as "Predator X". It had a massive skull and a bite force estimated to be four times greater than T-Rex.',
    habitat: 'Oceans',
    location: { name: 'Europe', lat: 50.0, lng: 10.0 },
    fun_fact: 'Its teeth were triangular in cross-section and razor sharp.',
    image_url: 'https://picsum.photos/seed/pliosaurus/800/600',
    anatomy: [{ feature: 'Jaws', description: 'Massive bite force.' }],
    stats: { intelligence: 5, speed: 8, defense: 5, attack: 10 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'liopleurodon',
    name: 'Liopleurodon',
    pronunciation: 'lie-oh-PLOO-row-don',
    meaning: 'Smooth-sided Tooth',
    period: 'Middle Jurassic',
    year: 1873,
    diet: 'Carnivore',
    group: 'Marine Reptiles',
    length_meters: 7,
    weight_tons: 1.5,
    description: 'A large pliosaur with four strong paddle-like limbs. It was an apex predator of the Jurassic seas.',
    habitat: 'Oceans',
    location: { name: 'Europe', lat: 48.0, lng: 2.0 },
    fun_fact: 'It could likely detect prey by scent underwater.',
    image_url: 'https://picsum.photos/seed/liopleurodon/800/600',
    anatomy: [{ feature: 'Flippers', description: 'Four powerful paddles.' }],
    stats: { intelligence: 5, speed: 9, defense: 4, attack: 9 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'kronosaurus',
    name: 'Kronosaurus',
    pronunciation: 'kro-no-SORE-us',
    meaning: 'Lizard of Kronos',
    period: 'Early Cretaceous',
    year: 1924,
    diet: 'Carnivore',
    group: 'Marine Reptiles',
    length_meters: 10,
    weight_tons: 11,
    description: 'Named after the Greek titan Kronos, this pliosaur had a massive head and hunted large prey including other plesiosaurs.',
    habitat: 'Oceans',
    location: { name: 'Australia', lat: -25.0, lng: 135.0 },
    fun_fact: 'Its head was nearly 3 meters (9 feet) long.',
    image_url: 'https://picsum.photos/seed/kronosaurus/800/600',
    anatomy: [{ feature: 'Teeth', description: 'Banana-sized conical teeth.' }],
    stats: { intelligence: 4, speed: 7, defense: 5, attack: 10 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'tylosaurus',
    name: 'Tylosaurus',
    pronunciation: 'tie-lo-SORE-us',
    meaning: 'Knob Lizard',
    period: 'Late Cretaceous',
    year: 1872,
    diet: 'Carnivore',
    group: 'Marine Reptiles',
    length_meters: 14,
    weight_tons: 8,
    description: 'A giant mosasaur that ruled the Western Interior Seaway. It used its snout as a battering ram to stun prey.',
    habitat: 'Shallow seas',
    location: { name: 'North America', lat: 40.0, lng: -100.0 },
    fun_fact: 'It ate sharks, fish, and even other smaller mosasaurs.',
    image_url: 'https://picsum.photos/seed/tylosaurus/800/600',
    anatomy: [{ feature: 'Snout', description: 'Reinforced for ramming.' }],
    stats: { intelligence: 5, speed: 8, defense: 5, attack: 9 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'ichthyosaurus',
    name: 'Ichthyosaurus',
    pronunciation: 'ick-thee-oh-SORE-us',
    meaning: 'Fish Lizard',
    period: 'Early Jurassic',
    year: 1821,
    diet: 'Carnivore',
    group: 'Marine Reptiles',
    length_meters: 2,
    weight_tons: 0.1,
    description: 'Resembling a modern dolphin, Ichthyosaurus was built for speed. It gave birth to live young.',
    habitat: 'Oceans',
    location: { name: 'Europe', lat: 51.0, lng: -1.0 },
    fun_fact: 'It had enormous eyes to see in deep, murky water.',
    image_url: 'https://picsum.photos/seed/ichthyosaurus/800/600',
    anatomy: [{ feature: 'Eyes', description: 'Huge scleral rings for deep diving.' }],
    stats: { intelligence: 6, speed: 9, defense: 2, attack: 4 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'thalattosuchians',
    name: 'Thalattosuchus',
    pronunciation: 'tha-lat-oh-SOO-kuss',
    meaning: 'Sea Crocodile',
    period: 'Jurassic',
    year: 1841,
    diet: 'Carnivore',
    group: 'Crocodylomorphs',
    length_meters: 4,
    weight_tons: 0.5,
    description: 'A marine crocodile fully adapted to life at sea with paddle-like limbs and a shark-like tail.',
    habitat: 'Oceans',
    location: { name: 'Europe', lat: 48.0, lng: 10.0 },
    fun_fact: 'Unlike modern crocodiles, it had smooth skin without bony armor to swim faster.',
    image_url: 'https://picsum.photos/seed/thalatto/800/600',
    anatomy: [{ feature: 'Tail', description: 'Fluke-like tail for propulsion.' }],
    stats: { intelligence: 4, speed: 7, defense: 3, attack: 6 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Water'
  },
  {
    id: 'sarcosuchus',
    name: 'Sarcosuchus',
    pronunciation: 'sar-koh-SOO-kuss',
    meaning: 'Flesh Crocodile',
    period: 'Early Cretaceous',
    year: 1966,
    diet: 'Carnivore',
    group: 'Crocodylomorphs',
    length_meters: 12,
    weight_tons: 8,
    description: 'Known as "SuperCroc", this massive crocodile lived in rivers and preyed on dinosaurs.',
    habitat: 'Rivers',
    location: { name: 'Africa', lat: 15.0, lng: 10.0 },
    fun_fact: 'It kept growing throughout its entire lifespan of 50-60 years.',
    image_url: 'https://picsum.photos/seed/sarcosuchus/800/600',
    anatomy: [{ feature: 'Jaws', description: 'Bulbous snout tip called a bulla.' }],
    stats: { intelligence: 3, speed: 4, defense: 9, attack: 10 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Water'
  },

  // Pterosaurs
  {
    id: 'aerodactylus',
    name: 'Aerodactylus',
    pronunciation: 'air-oh-DAK-til-us',
    meaning: 'Wind Finger',
    period: 'Late Jurassic',
    year: 1850,
    diet: 'Carnivore',
    group: 'Pterosaurs',
    length_meters: 1.2,
    weight_tons: 0.005,
    description: 'A small pterosaur from the Solnhofen limestone. It likely hunted insects and small fish.',
    habitat: 'Coastal lagoons',
    location: { name: 'Europe', lat: 49.0, lng: 11.0 },
    fun_fact: 'Yes, it shares a name with a famous Pokémon!',
    image_url: 'https://picsum.photos/seed/aerodactyl/800/600',
    anatomy: [{ feature: 'Teeth', description: 'Small cone-shaped teeth.' }],
    stats: { intelligence: 4, speed: 8, defense: 1, attack: 3 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Sky'
  },
  {
    id: 'arcticodactylus',
    name: 'Arcticodactylus',
    pronunciation: 'ark-tick-oh-DAK-til-us',
    meaning: 'Arctic Finger',
    period: 'Late Triassic',
    year: 1989,
    diet: 'Insectivore',
    group: 'Pterosaurs',
    length_meters: 0.5,
    weight_tons: 0.001,
    description: 'One of the earliest and smallest pterosaurs, discovered in Greenland.',
    habitat: 'Coastal',
    location: { name: 'Greenland', lat: 75.0, lng: -40.0 },
    fun_fact: 'It lived when Greenland was much warmer than today.',
    image_url: 'https://picsum.photos/seed/arctico/800/600',
    anatomy: [{ feature: 'Wings', description: 'Short wingspan suitable for maneuvering.' }],
    stats: { intelligence: 3, speed: 7, defense: 1, attack: 2 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Sky'
  },
  {
    id: 'barbaridactylus',
    name: 'Barbaridactylus',
    pronunciation: 'bar-bar-ee-DAK-til-us',
    meaning: 'Barbary Finger',
    period: 'Late Cretaceous',
    year: 2018,
    diet: 'Piscivore',
    group: 'Pterosaurs',
    length_meters: 4,
    weight_tons: 0.02,
    description: 'A nyctosaurid pterosaur from Morocco with a distinctive large crest.',
    habitat: 'Coastal',
    location: { name: 'Africa (Morocco)', lat: 31.0, lng: -7.0 },
    fun_fact: 'Its crest was antler-shaped.',
    image_url: 'https://picsum.photos/seed/barbari/800/600',
    anatomy: [{ feature: 'Crest', description: 'Very large and branched.' }],
    stats: { intelligence: 5, speed: 8, defense: 1, attack: 4 },
    showOnMap: false,
    hipAnatomy: 'Other',
    environment: 'Sky'
  },

  // Sauropods
  {
    id: 'apatosaurus',
    name: 'Apatosaurus',
    pronunciation: 'ah-PAT-oh-sore-us',
    meaning: 'Deceptive Lizard',
    period: 'Late Jurassic',
    year: 1877,
    diet: 'Herbivore',
    group: 'Sauropods',
    length_meters: 23,
    weight_tons: 25,
    description: 'Once mistakenly called Brontosaurus, this massive herbivore had a thick neck and whip-like tail.',
    habitat: 'Floodplains',
    location: { name: 'North America', lat: 40.0, lng: -105.0 },
    fun_fact: 'It swallowed stones (gastroliths) to help grind up food in its stomach.',
    image_url: 'https://picsum.photos/seed/apatosaurus/800/600',
    anatomy: [{ feature: 'Neck', description: 'Thick and muscular.' }],
    stats: { intelligence: 2, speed: 2, defense: 8, attack: 3 },
    showOnMap: false,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'supersaurus',
    name: 'Supersaurus',
    pronunciation: 'SOO-per-sore-us',
    meaning: 'Super Lizard',
    period: 'Late Jurassic',
    year: 1972,
    diet: 'Herbivore',
    group: 'Sauropods',
    length_meters: 34,
    weight_tons: 40,
    description: 'One of the longest land animals ever, potentially reaching up to 40 meters.',
    habitat: 'Floodplains',
    location: { name: 'North America', lat: 39.0, lng: -108.0 },
    fun_fact: 'Its neck alone was 15 meters long!',
    image_url: 'https://picsum.photos/seed/supersaurus/800/600',
    anatomy: [{ feature: 'Size', description: 'Extreme length.' }],
    stats: { intelligence: 2, speed: 1, defense: 7, attack: 2 },
    showOnMap: false,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },
  {
    id: 'camarasaurus',
    name: 'Camarasaurus',
    pronunciation: 'KAM-ah-rah-sore-us',
    meaning: 'Chambered Lizard',
    period: 'Late Jurassic',
    year: 1877,
    diet: 'Herbivore',
    group: 'Sauropods',
    length_meters: 18,
    weight_tons: 20,
    description: 'The most common sauropod of the Jurassic. It had a boxy head and spoon-shaped teeth.',
    habitat: 'Forests',
    location: { name: 'North America', lat: 40.0, lng: -109.0 },
    fun_fact: 'Its vertebrae had hollow chambers to reduce weight.',
    image_url: 'https://picsum.photos/seed/camarasaurus/800/600',
    anatomy: [{ feature: 'Teeth', description: 'Robust and spoon-shaped.' }],
    stats: { intelligence: 2, speed: 3, defense: 6, attack: 3 },
    showOnMap: false,
    hipAnatomy: 'Saurischian',
    environment: 'Land'
  },

  // Ceratopsians
  {
    id: 'pentaceratops',
    name: 'Pentaceratops',
    pronunciation: 'PEN-tah-SAIR-ah-tops',
    meaning: 'Five-horned Face',
    period: 'Late Cretaceous',
    year: 1923,
    diet: 'Herbivore',
    group: 'Ceratopsians',
    length_meters: 8,
    weight_tons: 5.5,
    description: 'It had the largest skull of any land animal, with a frill that reached halfway down its back.',
    habitat: 'Forests',
    location: { name: 'North America', lat: 36.0, lng: -108.0 },
    fun_fact: 'Despite its name, it really only had 3 horns; the other "horns" were cheek bones.',
    image_url: 'https://picsum.photos/seed/pentaceratops/800/600',
    anatomy: [{ feature: 'Frill', description: 'Enormous rectangular frill.' }],
    stats: { intelligence: 3, speed: 4, defense: 9, attack: 6 },
    showOnMap: false,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  },
  {
    id: 'monoclonius',
    name: 'Monoclonius',
    pronunciation: 'MON-oh-CLONE-ee-us',
    meaning: 'Single Sprout',
    period: 'Late Cretaceous',
    year: 1876,
    diet: 'Herbivore',
    group: 'Ceratopsians',
    length_meters: 5.5,
    weight_tons: 2,
    description: 'A controversial dinosaur similar to Centrosaurus, known for a single large horn on its nose.',
    habitat: 'Plains',
    location: { name: 'North America', lat: 48.0, lng: -110.0 },
    fun_fact: 'Many paleontologists believe it might just be a juvenile Centrosaurus.',
    image_url: 'https://picsum.photos/seed/monoclonius/800/600',
    anatomy: [{ feature: 'Nose Horn', description: 'Single prominent horn.' }],
    stats: { intelligence: 3, speed: 5, defense: 7, attack: 5 },
    showOnMap: false,
    hipAnatomy: 'Ornithischian',
    environment: 'Land'
  }
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Which dinosaur is known as the "Tyrant Lizard King"?',
    options: ['Triceratops', 'Tyrannosaurus Rex', 'Velociraptor', 'Stegosaurus'],
    correctAnswer: 1,
    explanation: 'Tyrannosaurus Rex literally translates to "Tyrant Lizard King" in Greek and Latin.'
  },
  {
    id: 'q2',
    question: 'What was the primary diet of a Triceratops?',
    options: ['Meat', 'Fish', 'Plants', 'Insects'],
    correctAnswer: 2,
    explanation: 'The Triceratops was a herbivore, using its beak to shear through tough vegetation.'
  },
  {
    id: 'q3',
    question: 'Which group does the Spinosaurus belong to?',
    options: ['Theropods', 'Sauropods', 'Spinosaurs', 'Ankylosaurs'],
    correctAnswer: 2,
    explanation: 'Spinosaurus is the namesake of the Spinosauridae family.'
  },
  {
    id: 'q4',
    question: 'How large was the brain of a Stegosaurus?',
    options: ['Size of a walnut', 'Size of a basketball', 'Size of a human brain', 'Size of a pea'],
    correctAnswer: 0,
    explanation: 'Despite its large body, the Stegosaurus had a brain roughly the size of a walnut.'
  },
  {
    id: 'q5',
    question: 'Where were the first Velociraptor fossils found?',
    options: ['North America', 'Antarctica', 'Gobi Desert (Mongolia)', 'Europe'],
    correctAnswer: 2,
    explanation: 'The first Velociraptor fossils were discovered in the Gobi Desert of Mongolia in 1923.'
  }
];
